Add stylings
tashisrael/React-Bookstore pull request #5
Opened 2022-11-11 19:22 UTC by tashisrael

Added stylings as per the zeplin design

2022-11-11 20:04 UTC, Lucas-Masaba requested changes
# Hello @tashisrael  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Linter checks passing ✔️ 
- Design looks similar to that as seen in the zeplin design but needs a few weeks 🏄 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-11 20:04 UTC, Lucas-Masaba commented on src/components/Book.js
> +        </div>
- [ ] In this project, you are required to parse the design as seen in the zeplin. Please make this card look similar to that in the  design.
### Your Implementation
![image](https://user-images.githubusercontent.com/45460192/201421994-57cb468a-fffc-49d4-85ef-c9da9554e615.png)
### Required
![image](https://user-images.githubusercontent.com/45460192/201422328-5965b6a0-4503-43da-854e-845094e3fb2c.png)

2022-11-11 20:04 UTC, Lucas-Masaba commented on src/components/Book.js
> +};
- [ ] The underline should be grey and should not span from one end of the page to another.
### Your implementation
![image](https://user-images.githubusercontent.com/45460192/201422610-8f9de2d1-6777-4c71-9faa-9d1a9455063d.png)

### Required
![image](https://user-images.githubusercontent.com/45460192/201422491-e3bb6f7d-0479-4598-be04-ad83ffaa86ae.png)

2022-11-11 20:04 UTC, Lucas-Masaba commented on src/components/addBook.js
>        </form>
- [ ] Please add similar widths for the input fields and spaces between them as seen in the original zeplin design
### Your Implementation
![image](https://user-images.githubusercontent.com/45460192/201422901-ed4b03ed-6782-408f-99f4-88336cc2ee47.png)
### Required
![image](https://user-images.githubusercontent.com/45460192/201422953-ca2ea9f1-812a-4cbf-8084-e48a8e7b7a76.png)

2022-11-12 11:29 UTC, sumairq approved these changes
### Hi @tashisrael , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-12 11:38 UTC, merged